#Path to your oh-my-zsh configuration.
ZSH=$HOME/.zsh/oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="oriol"

# Create ~/.cache folder structure
[ ! -d $HOME/.cache ] && mkdir -p $HOME/.cache
[ ! -d $HOME/.cache/bat ] && mkdir -p $HOME/.cache/bat
[ ! -d $HOME/.cache/lynx ] && mkdir -p $HOME/.cache/lynx
[ ! -d $HOME/.cache/tmux ] && mkdir -p $HOME/.cache/tmux
[ ! -d $HOME/.cache/tmux/tmux-resurrect ] && mkdir -p $HOME/.cache/tmux/tmux-resurrect
[ ! -d $HOME/.cache/zsh ] && mkdir -p $HOME/.cache/zsh

##
# History
##
HISTFILE=$HOME/.cache/zsh/history
HISTSIZE=50000
SAVEHIST=50000
setopt ALWAYS_TO_END            # when completing from the middle of a word, move the cursor to the end of the word    
setopt BANG_HIST                # !keyword
setopt COMPLETE_IN_WORD         # allow completion from within a word/phrase
setopt COMPLETEALIASES          # complete alisases
setopt CORRECT                  # spelling correction for commands
setopt HASH_LIST_ALL            # hash everything before completion
setopt HIST_IGNORE_ALL_DUPS     # no duplicate
setopt HIST_IGNORE_SPACE        # ignore space prefixed commands
setopt HIST_REDUCE_BLANKS       # trim blanks
setopt HIST_VERIFY              # show before executing history commands
setopt LIST_AMBIGUOUS           # complete as much of a completion until it gets ambiguous.
setopt EXTENDED_HISTORY         # save each command's beginning timestamp and the duration to the history file
setopt APPEND_HISTORY           # append to hostory when session ends
setopt NO_SHARE_HISTORY         # no share hist between sessions
setopt APPEND_HISTORY

##
# Pushd
##
setopt AUTO_PUSHD               # make cd push old dir in dir stack
setopt PUSHD_IGNORE_DUPS        # no duplicates in dir stack
setopt PUSHD_SILENT             # no dir stack after pushd or popd
setopt PUSHD_TO_HOME            # `pushd` = `pushd $HOME`

##
# Various
##
setopt AUTO_CD                  # if command is a path, cd into it
setopt AUTO_MENU                # Automatically use menu completion after the second consecutive request for completion
setopt AUTO_REMOVE_SLASH        # self explicit
setopt CHASE_LINKS              # resolve symlinks
setopt EXTENDED_GLOB            # activate complex pattern globbing
setopt FLOW_CONTROL             # Disables the use of ⌃S to stop terminal output and the use of ⌃Q to resume it
setopt GLOB_DOTS                # include dotfiles in globbing
setopt HIST_EXPIRE_DUPS_FIRST   # If trim needed, do it for the dups first, nou unique
setopt HIST_IGNORE_DUPS         # if executing same command in a row, save it only once
setopt MENU_COMPLETE            # Prevents the completion menu from showing even if AUTO_MENU is set
setopt NOTIFY                   # report the status of backgrounds jobs immediately
setopt PRINT_EXIT_VALUE         # print return value if non-zero
setopt PROMPT_SUBST             # Adds support for command substitution

# Al navegar per l'historial de comandes, deixar el cursor al final de la comanda
unsetopt GLOBAL_RCS

DISABLE_MAGIC_FUNCTIONS=true

plugins=(
    alias-finder
    bgnotify
    colored-man-pages
    command-not-found
    extract
    fast-syntax-highlighting
    forgit
    fzf-tab
    gitignore
    history-substring-search
    jsontools
    sudo
    urltools
    web-search
    z
    zsh-autosuggestions
    zsh-vim-mode
)

DISABLE_AUTO_TITLE="true"
autoload -U zmv

export ZSH_COMPDUMP="$HOME/.cache/zsh/zcompdump-$HOST-$ZSH_VERSION"
export LESSHISTFILE="$HOME/.cache/zsh/lesshst"

source $ZSH/oh-my-zsh.sh

# User configuration
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#155b6d"
export PATH=$HOME/.bin:/usr/local/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/bin:/usr/local/opt/sqlite/bin:$PATH
export VIRTUAL_ENV_DISABLE_PROMPT=disable

export HOMEBREW_CASK_OPTS="--appdir=/Applications"

export EVENT_NOKQUEUE=1

export VISUAL='nvim'
export EDITOR='nvim'

export LC_ALL=en_US.UTF-8

# Highlight man pages with bat
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# Utilitza Solarized dark per veure els fitxers
export BAT_THEME="solarizedDark"

export _Z_DATA="$HOME/.cache/zsh/z"
export FORGIT_GI_REPO_LOCAL="$HOME/.cache/zsh/forgit/gi/repos/dvcs/gitignore"
export FORGIT_GI_TEMPLATES="$FORGIT_GI_REPO_LOCAL/templates"

[ -f $HOME/.aliases.local.zsh ] && source $HOME/.aliases.local.zsh
[ -f $HOME/.profile ] && source $HOME/.profile
[ -f $HOME/.user_profile ] && source $HOME/.user_profile
[ -f $HOME/.zshrc.local ] && source $HOME/.zshrc.local

for f in ~/.zsh/autoload/*.zsh; do source $f; done

if [[ "$TERM" != "screen-256color" ]]; then
    tmux-start "$USER"
fi

########################################
# Bind keys for widgets
########################################
bindkey -v 

stty -ixon
stty stop undef

bindkey '^A' beginning-of-line
bindkey '^E' end-of-line

bindkey '\eF' forward-word
bindkey '\eB' backward-word

bindkey '^B' backward-kill-word

bindkey '^P' history-substring-search-up
bindkey '^N' history-substring-search-down

# Plugin configurations
function bgnotify_formatted {
  ## $1=exit_status, $2=command, $3=elapsed_time
  [ $1 -eq 0 ] && title="Has finished OK" || title="Has finished KO"
  bgnotify "$title -- after $3 s" "$2";
}

MODE_CURSOR_VIINS="#00ff00 blinking bar"
MODE_CURSOR_REPLACE="$MODE_CURSOR_VIINS #ff0000"
MODE_CURSOR_VICMD="green block"
MODE_CURSOR_SEARCH="#ff00ff steady underline"
MODE_CURSOR_VISUAL="$MODE_CURSOR_VICMD steady bar"
MODE_CURSOR_VLINE="$MODE_CURSOR_VISUAL #00ffff"

MODE_INDICATOR_VIINS='[INSERT]'
MODE_INDICATOR_VICMD='[NORMAL]'
MODE_INDICATOR_REPLACE='[REPLACE]'
MODE_INDICATOR_SEARCH='[SEARCH]'
MODE_INDICATOR_VISUAL='[VISUAL]'
MODE_INDICATOR_VLINE='[V-LINE]'

TMUX_PASSTHROUH=1
