#Path to your oh-my-zsh configuration.
ZSH=$HOME/.zsh/oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="oriol"

# Create ~/.cache folder structure
[ ! -d $HOME/.cache ] && mkdir -p $HOME/.cache
[ ! -d $HOME/.cache/bat ] && mkdir -p $HOME/.cache/bat
[ ! -d $HOME/.cache/lynx ] && mkdir -p $HOME/.cache/lynx
[ ! -d $HOME/.cache/tmux ] && mkdir -p $HOME/.cache/tmux
[ ! -d $HOME/.cache/tmux/tmux-resurrect ] && mkdir -p $HOME/.cache/tmux/tmux-resurrect
[ ! -d $HOME/.cache/zsh ] && mkdir -p $HOME/.cache/zsh

##
# History
##
HISTFILE=$HOME/.cache/zsh/history
HISTSIZE=50000
SAVEHIST=50000
setopt always_to_end            # when completing from the middle of a word, move the cursor to the end of the word    
setopt append_history           # append
setopt bang_hist                # !keyword
setopt complete_in_word         # allow completion from within a word/phrase
setopt completealiases          # complete alisases
setopt correct                  # spelling correction for commands
setopt extended_history         # save each command's beginning timestamp and the duration to the history file
setopt hash_list_all            # hash everything before completion
setopt hist_ignore_all_dups     # no duplicate
setopt hist_ignore_space        # ignore space prefixed commands
setopt hist_reduce_blanks       # trim blanks
setopt hist_verify              # show before executing history commands
setopt inc_append_history       # add commands as they are typed, don't wait until shell exit 
setopt list_ambiguous           # complete as much of a completion until it gets ambiguous.
setopt no_share_history         # share hist between sessions

##
# Pushd
##
setopt auto_pushd               # make cd push old dir in dir stack
setopt pushd_ignore_dups        # no duplicates in dir stack
setopt pushd_silent             # no dir stack after pushd or popd
setopt pushd_to_home            # `pushd` = `pushd $HOME`

##
# Various
##
setopt auto_cd                  # if command is a path, cd into it
setopt auto_menu                # Automatically use menu completion after the second consecutive request for completion
setopt auto_remove_slash        # self explicit
setopt chase_links              # resolve symlinks
setopt extended_glob            # activate complex pattern globbing
setopt flow_control             # Disables the use of ⌃S to stop terminal output and the use of ⌃Q to resume it
setopt glob_dots                # include dotfiles in globbing
setopt hist_expire_dups_first   # If trim needed, do it for the dups first, nou unique
setopt hist_ignore_dups         # if executing same command in a row, save it only once
setopt menu_complete            # Prevents the completion menu from showing even if AUTO_MENU is set
setopt notify                   # report the status of backgrounds jobs immediately
setopt print_exit_value         # print return value if non-zero
setopt prompt_subst             # Adds support for command substitution

DISABLE_MAGIC_FUNCTIONS=true

plugins=(
    alias-finder
    bgnotify
    colored-man-pages
    command-not-found
    extract
    fast-syntax-highlighting
    fzf-tab
    gitignore
    history-substring-search
    jsontools
    sudo
    urltools
    web-search
    z
    zsh-autosuggestions
    zsh-vim-mode
)

DISABLE_AUTO_TITLE="true"
autoload -U zmv

# Al navegar per l'historial de comandes, deixar el cursor al final de la comanda
unsetopt global_rcs

source $ZSH/oh-my-zsh.sh

# User configuration
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#155b6d"
export PATH=$HOME/.bin:/usr/local/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/bin:/usr/local/opt/sqlite/bin:$PATH
export VIRTUAL_ENV_DISABLE_PROMPT=disable

export HOMEBREW_CASK_OPTS="--appdir=/Applications"

export EVENT_NOKQUEUE=1

export VISUAL='nvim'
export EDITOR='nvim'

export LC_ALL=en_US.UTF-8

# Highlight man pages with bat
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# Utilitza Solarized dark per veure els fitxers
export BAT_THEME="solarizedDark"

export _Z_DATA="$HOME/.cache/zsh/z"




# Bind keys for widgets

bindkey -v 

# Allow using C-s in terminal
bindkey -r '\C-s'
stty -ixon
stty stop undef

# On autosugest command line, executes the current suggestion
# bindkey '^ ' autosuggest-accept
# bindkey '^[e' autosuggest-execute

# vi style incremental search
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line

bindkey '^B' backward-word
bindkey '^H' backward-kill-word

# Arrow up
bindkey '\e0A' history-search-backward
bindkey '\e[A' history-search-backward

# Arrow down
bindkey '\e0B' history-search-forward
bindkey '\e[B' history-search-forward

# Arrow right
bindkey '\e0C' forward-char
bindkey '\e[C' forward-char

# Arrow left
bindkey '\e0D' backward-char
bindkey '\e[D' backward-char

# Same as above, but with more vim-like traversal
bindkey '\C-k' history-search-backward
bindkey '\C-j' history-search-forward
bindkey '\C-h' backward-char
bindkey '\C-l' forward-char

bindkey '\e[1~' beginning-of-line
bindkey '\e[4~' end-of-line
bindkey '\eOF' end-of-line
bindkey '\eOH' beginning-of-line
bindkey '\e[3~' delete-char # Del
bindkey '\e[6~' end-of-history
bindkey '\e[5~' beginning-of-history

[ -f $HOME/.aliases.local.zsh ] && source $HOME/.aliases.local.zsh
[ -f $HOME/.zsh/lib/aliases.zsh ] && source $HOME/.zsh/lib/aliases.zsh
[ -f $HOME/.zsh/lib/fzf.zsh ] && source $HOME/.zsh/lib/fzf.zsh
[ -f $HOME/.zsh/lib/fzf-forgit.zsh ] && source $HOME/.zsh/lib/fzf-forgit.zsh
[ -f $HOME/.profile ] && source $HOME/.profile
[ -f $HOME/.user_profile ] && source $HOME/.user_profile
[ -f $HOME/.zshrc.local ] && source $HOME/.zshrc.local

source $HOME/.zsh/lib/autoload/*.zsh

if [[ "$TERM" != "screen-256color" ]]; then
    tmux-start "$USER"
fi

# zsh-history-substring-search key bindings
bindkey '^P' history-substring-search-up
bindkey '^N' history-substring-search-down


# Plugin configurations
function bgnotify_formatted {
  ## $1=exit_status, $2=command, $3=elapsed_time
  [ $1 -eq 0 ] && title="Has finished OK" || title="Has finished KO"
  bgnotify "$title -- after $3 s" "$2";
}

MODE_CURSOR_VIINS="#00ff00 blinking bar"
MODE_CURSOR_REPLACE="$MODE_CURSOR_VIINS #ff0000"
MODE_CURSOR_VICMD="green block"
MODE_CURSOR_SEARCH="#ff00ff steady underline"
MODE_CURSOR_VISUAL="$MODE_CURSOR_VICMD steady bar"
MODE_CURSOR_VLINE="$MODE_CURSOR_VISUAL #00ffff"

MODE_INDICATOR_VIINS='[INSERT]'
MODE_INDICATOR_VICMD='[NORMAL]'
MODE_INDICATOR_REPLACE='[REPLACE]'
MODE_INDICATOR_SEARCH='[SEARCH]'
MODE_INDICATOR_VISUAL='[VISUAL]'
MODE_INDICATOR_VLINE='[V-LINE]'

TMUX_PASSTHROUH=1
