# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="oriol"

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

#plugins=(git history-substring-search)
plugins=(
    colored-man
    common-aliases
    composer
    encode64
    extract
    fasd
    git
    git-extras
    git-flow-avh
    history
    jsontools
    osx
    pass
    symfony2
    tmuxinator
    vagrant
    zsh-completions
    zsh-syntax-highlighting
)

DISABLE_AUTO_TITLE="true"
autoload -U zmv
setopt correct

# I don't like every tab on my terminal sharing the same history.
setopt NO_SHARE_HISTORY
setopt APPEND_HISTORY

# Remember about a years worth of history (AWESOME)
SAVEHIST=10000
HISTSIZE=10000

# Al navegar per l'historial de comandes, deixar el cursor al final de la comanda
unsetopt global_rcs

source $ZSH/oh-my-zsh.sh

# User configuration

export PATH=$HOME/.bin:/usr/local/bin:/bin:/usr/sbin:/sbin:/usr/bin:$PATH
export VIRTUAL_ENV_DISABLE_PROMPT=disable
export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"

export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi
export VISUAL='vim'
export EDITOR='vim'

export WWW_HOME='http://www.google.com'

# Using the AUTOCD option, you can simply type the name of a directory, and it will become the current directory.
setopt AUTO_CD

bindkey -v 

# Allow using C-s in terminal
bindkey -r '\C-s'
stty -ixon
stty stop undef

# vi style incremental search
bindkey "^B" history-incremental-search-backward
bindkey "^F" history-incremental-search-forward

bindkey '^P' history-beginning-search-backward
bindkey '^N' history-beginning-search-forward
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line

# Arrow up
bindkey '\e0A' history-search-backward
bindkey '\e[A' history-search-backward

# Arrow down
bindkey '\e0B' history-search-forward
bindkey '\e[B' history-search-forward

# Arrow right
bindkey '\e0C' forward-char
bindkey '\e[C' forward-char

# Arrow left
bindkey '^H' backward-kill-word
bindkey '\e0D' backward-char
bindkey '\e[D' backward-char

# Same as above, but with more vim-like traversal
bindkey '\C-k' history-search-backward
bindkey '\C-j' history-search-forward
bindkey '\C-h' backward-char
bindkey '\C-l' forward-char

bindkey '\e[1~' beginning-of-line
bindkey '\e[4~' end-of-line
bindkey '\eOF' end-of-line
bindkey '\eOH' beginning-of-line
bindkey '\e[3~' delete-char # Del
bindkey '\e[6~' end-of-history
bindkey '\e[5~' beginning-of-history

[[ -f $HOME/.aliases ]] && source $HOME/.aliases
[[ -f $HOME/.aliases.local ]] && source $HOME/.aliases.local

# Common settings
[[ -f $HOME/.profile ]] && source $HOME/.profile
# User settings
[[ -f $HOME/.user_profile ]] && source $HOME/.user_profile

# Keypad
# 0 . Enter
bindkey -s "^[Op" "0"
bindkey -s "^[Ol" "."
bindkey -s "^[OM" "^M"
# 1 2 3
bindkey -s "^[Oq" "1"
bindkey -s "^[Or" "2"
bindkey -s "^[Os" "3"
# 4 5 6
bindkey -s "^[Ot" "4"
bindkey -s "^[Ou" "5"
bindkey -s "^[Ov" "6"
# 7 8 9
bindkey -s "^[Ow" "7"
bindkey -s "^[Ox" "8"
bindkey -s "^[Oy" "9"
# + -  * / =
bindkey -s "^[Ok" "+"
bindkey -s "^[Om" "-"
bindkey -s "^[Oj" "*"
bindkey -s "^[Oo" "/"
bindkey -s "^[OX" "="

if [[ `uname` == 'Linux' ]]; then
elif [[ `uname` == 'Darwin' ]]; then
    source $HOME/.zshrc-osx
fi

# TheFuck start
eval "$(thefuck --alias)"
